#!/bin/sh

git remote update;

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
# BASE=$(git merge-base @ "$UPSTREAM")

# echo "Local: " + $LOCAL;
# echo "Remote: " + $REMOTE;
# echo "Base: " + $BASE;

if [ $LOCAL != $REMOTE ]; then
    echo "Update is needed";
    exit 1;
fi

exit 0;