#!/bin/sh

CONTEXT_FILE_PATTERN="src/main/webapp/META-INF/context.xml";

if git diff --cached --name-only | grep --quiet "$CONTEXT_FILE_PATTERN"
then
    echo "context.xml changes detected";
    exit 1;
fi

git remote update;

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
# BASE=$(git merge-base @ "$UPSTREAM")

# echo "Local: " + $LOCAL;
# echo "Remote: " + $REMOTE;
# echo "Base: " + $BASE;

if [ $LOCAL != $REMOTE ]; then
    echo "Update is needed";
    exit 1;
fi

exit 0;